### ISSUE TITLE
Merge Access

### ISSUE THREAD

**Issue by Inspector-Butters** [eth-protocol-fellows/cohort-five#24]
I was thinking about asking the organizers for merge access to be able to merge the PRs that don't need much supervision. but there was no clear instruction to where and how I should propose this request. So I thought I open an issue here. 
This could possibly be an open issue for the length of the cohort, so anyone who wants to be granted merge access can request it here.
I also took it upon myself to create a general guideline for merging PRs.
### Guidelines for merging a PR
- The proposed updates should be related the EPF Cohort within the defined [structures](https://github.com/eth-protocol-fellows/cohort-five/blob/main/program-guide/repo-guide.md)
- The changes should not break formatting, or contain obvious oversights.
- The links in the updates should be accessible to the public.
- Proposed changes should not affect other fellows' data in a harmful way. 
- If in doubt about merging a PR, ask others inputs. 

please feel free to propose changes.

**Comment by taxmeifyoucan** [comment]
Information on how PRs are handled is, or should be, all here https://github.com/eth-protocol-fellows/cohort-five/blob/main/program-guide/repo-guide.md

More guidelines will be given at EPF intro call and if you want to contribute to the above guide, it should be based on information from there. I will be closing this but if you find it unresolved, feel free to contribute there.
Generally its quite trivial because vast majority of PRs should be just adding dev updates which is well explained elsewhere and only requires basic knowledge of git. 
Regarding the merge access itself, we are not going to grant access widely, at least not at first, because all dev updates need to be reviewed by us.
